### ISSUE TITLE
Scripts too old now

### ISSUE THREAD

**Issue by alexguillon** [KennyWdev/PortalHoloLens#1]
Hi, 
I'm a fan of your project and I've just updated the scripts because they're not working anymore. It's working now on the last version of Unity. Can you please add me to the collaborators so that I can make a commit ?

Thank you !

**Comment by KennyWdev** [comment]
Sure thing :) I'm surprised people are still contributing to the project,
thank you for updating the scripts!

**Comment by alexguillon** [comment]
Perfect !
I updated the scripts and also changed the README ;)
